# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end

  # tools installation
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y wget vim zip unzip git 
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo 'export TZ="/usr/share/zoneinfo/Europe/Moscow"' >> .bash_profile

  SHELL

  end
